### ISSUE TITLE
Too many reads in get-winner-block

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin#74] opened 2021-06-03 08:36 UTC
CostBalanceExceeded(ExecutionCost { write_length: 0, write_count: 0, read_length: 52547, **read_count: 31**, runtime: 74566000 }, ExecutionCost { write_length: 0, write_count: 0, read_length: 100000, read_count: 30, runtime: 1000000000 })

![Screenshot from 2021-06-03 10-36-06](https://user-images.githubusercontent.com/1449049/120614454-8b1c0400-c457-11eb-855f-60d49aa39a26.png)

**Comment by friedger** [comment] 2021-06-03 09:08
Should we cut down number of miners to 64?

**Comment by LNow** [comment] 2021-06-03 11:14
It's caused by totally different execution costs limits imposed on read only functions:
https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/net/connection.rs#L435-L441

Even if we cut down number of miners to 64 we will exceed 30 read_count limit, because after recent changes miners commitment are stored in map, so to read them we have to call `map-get?` as many times as we have miners.

**Comment by philipdesmedt** [comment] 2021-06-03 11:45
This should be fixed in the new release that is coming out today AFAIK, check stacks-blockchain 2.0.11.1 (I think) release notes

**Comment by LNow** [comment] 2021-06-12 13:17
At this moment it is impossible to refactor this function and go below 30 read_count's limit.
Thankfully @friedger found a way to calculate same thing on the client side.

**Closed** 2021-07-24 16:55 UTC
Labels: Normal
